<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                'category_name'=>'Food',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Clothes',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Fruits',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Purchase',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Traffic',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Accommodation',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Travel',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Drinks',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Water and electricity costs',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Gift',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Hobbies',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Car',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Social activities',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Insurance',
                'category_type'=>'expense',
                'is_default'=>true
            ],

            [
                'category_name'=>'Office',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Books',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Cigarette',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Pet',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Beauty',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Hamburger',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Education',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Vegetables',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Snacks',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Telephone tax',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Babe',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Tax',
                'category_type'=>'expense',
                'is_default'=>true
            ]
            ,
            [
                'category_name'=>'Sport',
                'category_type'=>'expense',
                'is_default'=>true
            ]
            ,
            [
                'category_name'=>'Digital',
                'category_type'=>'expense',
                'is_default'=>true
            ] ,
            [
                'category_name'=>'Health',
                'category_type'=>'expense',
                'is_default'=>true
            ],
            [
                'category_name'=>'Location',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Salary',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Others',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Endowment',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Dividends',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Refund',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Prime',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Sale',
                'category_type'=>'income',
                'is_default'=>true
            ],
            [
                'category_name'=>'Coupon',
                'category_type'=>'income',
                'is_default'=>true
            ]
            ];
            Category::insert($categories);
    }
}
